### ISSUE TITLE
The gem fails

### ISSUE THREAD

**Issue by rwz** [cryptosphere/rbnacl-libsodium#16]
In one of out PRs we've bumped the gem from version 1.0.11 to 1.0.13 and all our CIs failed with this trace:

```
LoadError: Could not open library 'sodium': sodium: cannot open shared object file: No such file or directory.
Could not open library 'libsodium.so': libsodium.so: cannot open shared object file: No such file or directory
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium.rb:12:in `extended'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:9:in `extend'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
/home/travis/build/heroku/api/vendor/bundle/ruby/2.4.0/gems/rbnacl-3.4.0/lib/rbnacl.rb:4:in `<top (required)>'
```

Let me know if there's anything else I can provide to help debugging this.

**Comment by rwz** [comment]
Actually nevermind, seems like the issue is caused by JWT 2.1.0. We're seeing same behavior on 1.0.11 as well. Sorry, false alarm.
