### ISSUE TITLE
Installation fails on Windows specifically

### ISSUE THREAD

**Issue by meew0** [cryptosphere/rbnacl-libsodium#6]
Hello, I'm using this gem for a project and I've successfully installed it on Linux many times, but every time I try to install it on Windows, I get this error:

```
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rbnacl-libsodium:
        ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160203-2572-1thjob5.rb extconf.rb
extconf.rb:4:in `sys': ERROR: './configure --prefix=C:/Ruby22/lib/ruby/gems/2.2.
0/gems/rbnacl-libsodium-1.0.8/vendor/libsodium/dist' failed (RuntimeError)
        from extconf.rb:22:in `block in <main>'
        from extconf.rb:21:in `chdir'
        from extconf.rb:21:in `<main>'
 -- ./configure --prefix=C:/Ruby22/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0
.8/vendor/libsodium/dist

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/rbnacl-lib
sodium-1.0.8 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/rbn
acl-libsodium-1.0.8/gem_make.out
```

The content of said `gem_make.out`:
```
C:/Ruby22/bin/ruby.exe -r ./siteconf20160203-2572-1thjob5.rb extconf.rb
extconf.rb:4:in `sys': ERROR: './configure --prefix=C:/Ruby22/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.8/vendor/libsodium/dist' failed (RuntimeError)
	from extconf.rb:22:in `block in <main>'
	from extconf.rb:21:in `chdir'
	from extconf.rb:21:in `<main>'
 -- ./configure --prefix=C:/Ruby22/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.8/vendor/libsodium/dist

extconf failed, exit code 1
```

I'm definitely doing something wrong here, but I have no idea what. I've verified the DevKit works by installing another gem with native extensions (`json`). I appreciate any help or guidance, thanks!

**Comment by tarcieri** [comment]
It appears the `configure` script in libsodium is failing. Can you cd to `C:/Ruby22/lib/ruby/gems/2.2.0/gems/rbnacl-libsodium-1.0.8/vendor/libsodium/dist` and try running it by hand?

**Comment by meew0** [comment]
There's no `dist` folder at all in the `libsodium` folder, only a `dist-build` one, which doesn't contain any `./configure` file but rather ones that appear to be platform specific:

```
03.02.2016  21:42    <DIR>          .
03.02.2016  21:42    <DIR>          ..
03.02.2016  21:42               171 android-arm.sh
03.02.2016  21:42               208 android-armv7-a.sh
03.02.2016  21:42               161 android-armv8-a.sh
03.02.2016  21:42             1.149 android-build.sh
03.02.2016  21:42               158 android-mips32.sh
03.02.2016  21:42               164 android-mips64.sh
03.02.2016  21:42               160 android-x86-64.sh
03.02.2016  21:42               153 android-x86.sh
03.02.2016  21:42             5.177 emscripten.sh
03.02.2016  21:42             3.222 ios.sh
03.02.2016  21:42               259 Makefile.am
03.02.2016  21:42            13.157 Makefile.in
03.02.2016  21:42               293 msys2-win32.sh
03.02.2016  21:42               279 msys2-win64.sh
03.02.2016  21:42               818 nativeclient.sh
03.02.2016  21:42               560 osx.sh
```
Should I try running the one for `win32` or are these not the right ones?

**Comment by tarcieri** [comment]
Not sure offhand ¯\\_(ツ)_/¯

**Comment by shirosaki** [comment]
I got same issue.
Shell is not executed by `system` on Windows.
Adding `sh` works for me.

```patch
diff --git a/ext/rbnacl/extconf.rb b/ext/rbnacl/extconf.rb
index db16ea6..b5db126 100644
--- a/ext/rbnacl/extconf.rb
+++ b/ext/rbnacl/extconf.rb
@@ -19,7 +19,7 @@ LIBSODIUM_DIR = File.expand_path(File.join(CWD, '..', '..', 'vendor', 'libsodium
 MAKE = ENV['MAKE'] || ENV['make'] || "make"
 
 Dir.chdir(LIBSODIUM_DIR) do
-  sys("./configure --prefix=#{LIBSODIUM_DIR}/dist")
+  sys("sh -c \"./configure --prefix=#{LIBSODIUM_DIR}/dist\"")
   sys(MAKE)
   sys("#{MAKE} install")
 end
```

**Comment by shirosaki** [comment]
After I installed `require` causes errors.

```sh
> ruby -r"rbnacl/libsodium" -e '0'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-libsodium-.0.8/vendor/libsodium/dist/lib/libsodium.so': 指定 (LoadError)ールが見つかりません。
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium.rb:10:in `extended'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `extend'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-3.3.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-3.3.0/lib/rbnacl.rb:4:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rbnacl-libsodium-1.0.8/lib/rbnacl/libsodium.rb:11:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
```


`dist/lib/libsodium.so` doesn't exist.
To load library file on Windows copying dll file is needed.

```patch
diff --git a/ext/rbnacl/extconf.rb b/ext/rbnacl/extconf.rb
index b5db126..6ffef99 100644
--- a/ext/rbnacl/extconf.rb
+++ b/ext/rbnacl/extconf.rb
@@ -22,6 +22,7 @@ Dir.chdir(LIBSODIUM_DIR) do
   sys("sh -c \"./configure --prefix=#{LIBSODIUM_DIR}/dist\"")
   sys(MAKE)
   sys("#{MAKE} install")
+  sys("cp dist/bin/*.dll dist/lib/libsodium.so")
 end
 
 File.open("Makefile", "w") do |f|
```
